### ISSUE TITLE
Code revision

### ISSUE THREAD

**Issue by paulhamsh** [Celticpure/KATBOX-MIDI#1]
Hi Rory
This compiles - no idea if it will work!

```
#include <SPI.h>
#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>
#include <Fonts/FreeSans9pt7b.h>

// Control Surface:
#include <Control_Surface.h>
#include <AH/Hardware/MultiPurposeButton.hpp> //FOR USING MULTIPURPOSE BUTTON FUNCTION

BluetoothMIDI_Interface midi;                 //TYPE OF INTERFACE USED TO COMMUNICATE

// DISPLAY:
Adafruit_SSD1306 display(-1);

MultiPurposeButton btn1{15};      //BTN No.1
MultiPurposeButton btn2{19};      //BTN No.2
MultiPurposeButton btn3{4};       //BTN No.3
MultiPurposeButton btn4{5};       //BTN No.4

int new_button, old_button;
char str_buf[30];

void btn_disp(){
  if (new_button != old_button) {
    old_button = new_button;
    display.fillRect(0, 40, 100, 40, BLACK);
    sprintf(str_buf, "PATCH %d", new_button);
    display.setCursor(0, 40);
    display.print(str_buf);       
    display.display();
  }
}

void multibtn()
{
  switch (btn1.update()) {      //BTN No.1
    case btn1.PressStart:
      Control_Surface.sendControlChange({MIDI_CC::General_Purpose_Controller_1, CHANNEL_1}, 0); 
      new_button = 1;
      break;
    case btn1.LongPress:
      Control_Surface.sendControlChange({MIDI_CC::General_Purpose_Controller_2, CHANNEL_1}, 0);
      new_button = 1;
      break;
  }
  switch (btn2.update()) {      //BTN No.2
    case btn2.PressStart:
      Control_Surface.sendControlChange({MIDI_CC::General_Purpose_Controller_3, CHANNEL_2}, 0);
      new_button = 2;
      break;
    case btn2.LongPress:
      Control_Surface.sendControlChange({MIDI_CC::General_Purpose_Controller_4, CHANNEL_2}, 0);
      new_button = 2;
      break;
  }
  switch (btn3.update()) {      //BTN No.3
    case btn3.PressStart:
      Control_Surface.sendControlChange({MIDI_CC::General_Purpose_Controller_5, CHANNEL_3}, 0);
      new_button = 3;
      break;
    case btn3.LongPress:
      Control_Surface.sendControlChange({MIDI_CC::General_Purpose_Controller_6, CHANNEL_3}, 0);
      new_button = 3;
      break;
  }
  switch (btn4.update()) {      //BTN No.4
    case btn4.PressStart:
      Control_Surface.sendControlChange({MIDI_CC::General_Purpose_Controller_7, CHANNEL_4}, 0);
      new_button = 4;
      break;
    case btn4.LongPress:
      Control_Surface.sendControlChange({MIDI_CC::General_Purpose_Controller_8, CHANNEL_4}, 0);
      new_button = 4;
      break;
  }
}


void setup() {
  Serial.begin (9600);                        // initialize serial communication:

  display.begin(SSD1306_SWITCHCAPVCC, 0x3C);  // initialize with the I2C addr 0x3C
  display.clearDisplay();                     // Clear the buffer.
  display.setFont(&FreeSans9pt7b);            // Set Font

  Control_Surface.begin();                    // Set Control Surface
  btn1.setLongPressDelay(1000); 
  btn2.setLongPressDelay(1000); 
  btn3.setLongPressDelay(1000); 
  btn4.setLongPressDelay(1000);
  btn1.setMultiPressDelay(400); 
  btn2.setMultiPressDelay(400); 
  btn3.setMultiPressDelay(400); 
  btn4.setMultiPressDelay(400);
  btn1.begin(); 
  btn2.begin(); 
  btn3.begin(); 
  btn4.begin();

  display.setTextColor(WHITE, BLACK);
  display.setCursor(0, 15);
  display.println("KATBOX MIDI");
  display.display();

  old_button = 0;
  new_button = 0;
}

void loop() {
  Control_Surface.loop();
  multibtn();
  btn_disp();
}

```

**Comment by paulhamsh** [comment]
Also it seems creating a button sets it to PULLUP anyway:

void Button::begin() { ExtIO::pinMode(pin, INPUT_PULLUP); }

So the other button parts should not be needed.

**Comment by Celticpure** [comment]
Thank you Paul, this code compile and uploads just fine to my ESP32 Devkit V1. ControlChanges work as they should and are being transmitted and checked via Lightblue for Android. 
![Screenshot_2022-11-15-11-50-05-368_com punchthrough lightblueexplorer](https://user-images.githubusercontent.com/96823448/201912743-359b859d-e3e6-44a6-9cf8-78ee5d21cef2.jpg)

 However I am getting the typical issue that I keep getting stuck at. The overlay of the "PATCH" number - i.e. it overwrites the previous PATCH No, without updating it to the new one. You can see this from the phot attached the actual PATCH number is overlaying the pervious one thus resulting in gobildigook etc etc.. The text/screen flicker on button press has stopped at least which was driving me slightly more insane than normal..
![IMG_20221115_114253](https://user-images.githubusercontent.com/96823448/201911652-d2d9b8c0-2c02-4832-9c52-855daf8dfd08.jpg)

**Comment by paulhamsh** [comment]
Ok - try changing this line:      
```display.fillRect(0, 40, 100, 40, BLACK);```

it is fillRect(x, y, w, h, colour) so it mustn't be reaching over the number bit. Change w and h - make them bigger. I thought 100 for a 128 display would be ok, but perhaps the h needs to be more.

Try making it WHITE then it will show where it is writing the rectangle - then you can change it

**Comment by Celticpure** [comment]
Ok, I get what your trying to do now. I did read about the fillRect command but could never find a clear enough example for my brain to understand.

The line has now been changed to:
` display.fillRect(66, 27, 12, 17, BLACK);`
and the button press is clear and as it should be - EXCELLENT!

Now next question - if i was to give the end user the option to move the "PATCH" no. text in terms of its alignment (left, centre, right etc) how or could the above fillRect(x, y, w, h, colour) move with the alignment command?

https://user-images.githubusercontent.com/96823448/201927995-6de15f03-cc55-4b85-8186-23360459e907.mp4

**Comment by paulhamsh** [comment]
Odd - your rectangle seems to be from (66, 27) to (78, 44)
And PATCH is at (0, 40) - so left justified and 40 down.
Which makes it weird that the rectangle covers the number - as it only reaches past the 44 lines down.
I would have thought it should be:

display.fillRect(66, 40, 12, 57, BLACK);

I get going further across, just not less far down!


You could try using this to see where the text actually is:

tft.getTextBounds(string, x, y, &x1, &y1, &w, &h);

Anyway, you need to move the rectangle appropriately when you move the text - perhaps use an offset from the start of the text you use in setCursor

setCursor(a,b);  // 0,40
display.fillRect(a+66, b+27, 12, 17, BLACK);

**Comment by Celticpure** [comment]
Ok my bad, I tried and succeeded in just having fillRect over the patch "no." only. but I see now you had the FillRect over both PATCH and No. text. I have reverted the postion of the fillRect to:
`display.fillRect(0, 20, 100, 40, BLACK)`;

The display is the larger display OLED 2.42" that David Thompson used for his Sparkbox build - so this may influence different x,y locations possibly.

**Comment by paulhamsh** [comment]
It's weird - perhaps the setCursor is for bottom left of the text, not top of the text - I see you have setCursor(0, 15) for the first line and that is right at the top of the screen. But I can't google any document that says that!

Which makes it a bit more complex, but the same offset idea can apply. Just use (a,b) for the text, and an offset for the clearing box.

Or if it is too much, just .clear() the display and re-draw it all - it is only two lines after all

**Comment by Celticpure** [comment]
Paul - I will close this issue as it has brought the code to a new level - for the better. What I want to explore next is possibly using "Banks" to have the 4 buttons do something else when say 2 particular buttons are pressed together etc. this would then activate the Booster/FX/Reverb settings.

**Comment by paulhamsh** [comment]
Just a final point - it seems if you use a font, then setcursor is bottom left, and if you don't set a font, it it top left!
Seems like that anyway.

Found this - that is exactly what it does.

https://learn.adafruit.com/adafruit-gfx-graphics-library/using-fonts
